



version: 2


description: Lightweight Terraform Orb, not intended for generic use



    
jobs:

  build:
    docker:
      - image: hashicorp/terraform:light      

    steps:
      - checkout:
          path:  ~/gcp            
      - run: cd ~/gcp &&  terraform init
      - run: pwd   
     
