



version: 2


description: Lightweight Terraform Orb, not intended for generic use



    
jobs:

  build:
    docker:
      - image: hashicorp/terraform:light      

    steps:        
      - run: cd ~/gcp &&  terraform init
      - run: cd ~/gcp && terraform plan    
      - run: cd ~/gcp && terraform apply  
