



version: 2


description: Lightweight Terraform Orb, not intended for generic use

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:light
    working_directory:  ~/gcp/terraform




commands:
  tf:
    parameters:
      command:
        type: string
    steps:
      - run:
          name: terraform << parameters.command >>
          command: terraform << parameters.command >>




jobs:
  validate:
    executor: terraform
    steps:
      - checkout
      - init
      - tf:
          command: validate
