
version: 2

references:


default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
    BASH_ENV: /root/.bashrc

base_image: &base_image
  hashicorp/terraform:light


working_directory: &working_directory
  ~/gcp/terraform


terraform_init: &terraform_init
  run:
    name: terraform init
    command: |

      terraform init


apply_job: &apply_job
  steps:
    - *terraform_init
    - attach_workspace:
        at: *working_directory
