



version: 2


description: Lightweight Terraform Orb, not intended for generic use



    
jobs:

  build:
    docker:
      - image: hashicorp/terraform:light      

    steps:        
      - run: cd ~/terraform &&  terraform init
      - run: cd ~/terraform && terraform plan
      - run: cd ~/terraform && terraform apply       
