version: 2

terraform: &terraform
  docker
    -  image: hashicorp/terraform:0.12.0
  working_directory: /tmp/workspace/terraform


jobs:
  validate:
    <<: *terraform
    steps
      - checkout
      - run:
          name: terraform init
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform init -input=false -backend=false) || exit 1; done
      - run: 
          name: terraform plan 
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && terraform plan -input=false -backend=false) || exit 1; done
      - persist_to_workspace:
          root: .
          paths: .



workflows:
  version: 2
  build:
    jobs:
      - validate
#      - plan_examples
#      - approve
#      - release

