version: 2.1

workflows:
  tf:
    jobs:
      - tf/validate:
          name: validate
      - tf/plan:
          name: plan
          requires:
            - validate
      - tf/apply:
          name: apply
          requires:
            - plan
          filters:
            branches:
              only: master

